cloud:
  aws:
    credentials:
      secret-key: VublYe4oPV6EFlRPCchF7/qwizH8iSE6jxmpNuBP
      access-key: AKIAQULB357LVX5GQOOP
      instanceProfile: 'true'
    s3:
      bucket: saessak-s3
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'